# Generated by Django 4.2.1 on 2025-01-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('session_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pagestat',
            name='visit_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagestat',
            name='visitor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='page_stats', to='website.visitor'),
            preserve_default=False,
        ),
    ]
